apiVersion: v1
kind: Pod
metadata:
  name: bind
  labels:
    name: bind
spec:
  containers:
    - name: bind
      image: quay.io/sameersbn/bind
      env:
        - name: WEBMIN_ENABLED
          value: false
      ports:
        - containerPort: 53
          protocol: UDP
